#\u914D\u7F6E\u6839\u8DEF\u5F84
server:
  servlet:
    context-path: /web

#Druid \u6570\u636E\u6E90\u914D\u7F6E
spring:
  datasource:
    # Druid \u8FDE\u63A5\u6C60
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # \u6570\u636E\u5E93\u8FDE\u63A5\u4FE1\u606F
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.0.109:3306/springboot?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
      username: root
      password: 123456a?
      # \u8FDE\u63A5\u6C60\u914D\u7F6E
      initial-size: 5
      min-idle: 5
      max-active: 50
      # \u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4
      max-wait: 5000
      # \u914D\u7F6E\u95F4\u9694\u591A\u4E45\u624D\u8FDB\u884C\u4E00\u6B21\u68C0\u6D4B\uFF0C\u68C0\u6D4B\u9700\u8981\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
      time-between-eviction-runs-millis: 6000
      # \u914D\u7F6E\u8FDE\u63A5\u5728\u6C60\u4E2D\u7684\u6700\u5C0F\u751F\u5B58\u65F6\u95F4
      min-evictable-idle-time-millis: 300000
      # \u68C0\u6D4B\u662F\u5426\u4E3A\u6709\u6548SQL
      validation-query: select 'x'
      # \u6D4B\u8BD5\u8FDE\u63A5( \u5F00\u542F\u964D\u4F4E\u6027\u80FD )
      test-on-borrow: false
      test-on-return: false
      test-while-idle: false
      # \u72B6\u6001\u76D1\u63A7
      filter:
        stat:
        enabled: true
        db-type: mysql
        log-slow-sql: true
        slow-sql-millis: 2000
      # \u76D1\u63A7\u8FC7\u6EE4\u5668
      web-stat-filter:
        enabled: true
        exclusions:
          - "*.js"
          - "*.gif"
          - "*.jpg"
          - "*.png"
          - "*.css"
          - "*.ico"
          - "/druid/*"
      # druid \u76D1\u63A7\u9875\u9762
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: root
        login-password: root

# mybatis \u914D\u7F6E \u2014\u2014 \u82E5\u914D\u7F6E\u5B8C\u6587\u4EF6\u8DEF\u5F84\u6B63\u786E\uFF0C\u65E0\u6CD5\u751F\u6548\uFF0C\u4F7F\u7528maven clean \u4E4B\u540E\u91CD\u542F\u9879\u76EE
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml