server:
  port: 8848
spring:
  security:
    user:
      name: penguin
      password: night
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.107:3306/mall?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: 123456a?

